// SYNTHETIC demo cohort (25). These are invented people, NOT real individuals, and their URLs do not resolve.
// They exist only so the pre-run demo works in an environment where LinkedIn/Instagram are unreachable.
// Replace with real people via data/cohort.csv + `node scripts/ingest.mjs` (see README).
const P = (name, slug, headline, location, about, exp, ig, bio, posts) => ({
  slug, linkedin: { ok: true, via: 'synthetic', name, headline, location, about, experience: exp.map(([title, company]) => ({ title, company })), education: [], skills: [] },
  instagram: { ok: true, via: 'synthetic', username: ig, fullName: name, bio, posts, hashtags: [] },
});
export default [
  P('Maya Okafor', 'maya-okafor-demo', 'Founder & CEO at Lumen Health', 'New York, United States', 'Building clinical software that nurses actually like. Led a team from 3 to 40 and launched our Series A. Mentor for first-gen founders.', [['Founder & CEO', 'Lumen Health']], 'maya.builds', '📍 NYC · founder · long runs & longer dinners', ['Sunday long run in Central Park, half marathon in 6 weeks', 'Hosted 12 friends for dinner tonight, recipe in stories', 'Board meeting then a 5am spin class, this is fine', 'Mentoring hour with first-gen founders is the best part of my week']),
  P('Daniel Reyes', 'daniel-reyes-demo', 'Staff Machine Learning Engineer at Helix Labs', 'San Francisco, United States', 'Research-minded engineer working on LLM evaluation. I like rigor, clean data, and explaining systems to people who did not ask.', [['Staff ML Engineer', 'Helix Labs']], 'danny.ml', 'bouldering · coffee nerd · quiet weekends', ['Bouldering V6 project finally sent', 'Espresso dial-in day, 18g in 36g out', 'Reading a paper on neural scaling at a cafe, total rabbit hole', 'Quiet Sunday, journal, long walk with the dog']),
  P('Priya Nair', 'priya-nair-demo', 'Product Design Lead at Bloom', 'London, United Kingdom', 'Designer obsessed with typography and calm interfaces. I lead a design team of 8 and teach workshops on product design.', [['Product Design Lead', 'Bloom']], 'priya.designs', 'design · ceramics · gallery hopping · museum Sundays', ['New ceramics batch from the studio', 'Tate Modern again, sketching in the galleries', 'Typography rabbit hole: why this kerning feels kind', 'Film camera walk through Shoreditch']),
  P('Marcus Bell', 'marcus-bell-demo', 'Partner at Northbridge Capital', 'New York, United States', 'Investing in growth-stage software. Markets, models and metrics. Promoted to partner after leading three exits.', [['Partner', 'Northbridge Capital']], 'marcusbell', '📍 NYC · markets · wine · looking for something serious', ['Rooftop drinks, negroni debate on rates', 'Wine tasting weekend in Finger Lakes', 'Marathon training: 5am miles before the market opens', 'Looking for someone serious about building a life together']),
  P('Sofia Lindqvist', 'sofia-lindqvist-demo', 'Climate Policy Advisor at GreenBridge', 'Stockholm, Sweden', 'Working on renewable energy policy and carbon markets. Volunteer with a community nonprofit. Care deeply about the commons.', [['Climate Policy Advisor', 'GreenBridge']], 'sofia.outdoors', 'hiking · skiing · camping · climate nerd', ['Backpacking trip in Lapland, sunrise over the fjell', 'Volunteering at the community kitchen again', 'Skiing weekend with friends', 'Reading about clean energy transition at the lake']),
  P('Jonah Weiss', 'jonah-weiss-demo', 'Comedy Writer & Product Manager at Streamly', 'Chicago, United States', 'PM by day, improv and stand-up by night. I believe a good pun can fix a roadmap.', [['Senior Product Manager', 'Streamly']], 'jonah.jokes', 'improv · stand-up · board games · chaos goblin', ['Improv show tonight, lol the crowd was great', 'Board game night hosting, 8 friends, haha chaos', 'Stand-up open mic set, bombed and loved it', 'Meme of the week, joke about standups']),
  P('Aiko Tanaka', 'aiko-tanaka-demo', 'Research Scientist, Computational Biology at Genova', 'San Francisco, United States', 'PhD in biology. I build models of protein folding. I love careful experiments and quiet thinking.', [['Research Scientist', 'Genova']], 'aiko.lab', 'science · yoga · meditation · cozy homebody', ['Morning yoga and meditation before the lab', 'Reading at home with tea, introvert weekend', 'New piano piece, slow practice', 'Journal entry on why research teaches patience']),
  P('Tomás Herrera', 'tomas-herrera-demo', 'Executive Chef & Co-founder at Brasa', 'Austin, United States', 'Cooking is how I show care. Co-founded a restaurant, mentor young cooks, and host long tables with friends.', [['Executive Chef & Co-founder', 'Brasa']], 'chef.tomas', 'cooking · restaurant life · taco obsessed · live music', ['Tasting menu tonight at Brasa, grateful for the team', 'Taco crawl on a Sunday with friends', 'Live music at the venue after service, festival season', 'Sourdough experiments and a recipe for family']),
  P('Hannah Brooks', 'hannah-brooks-demo', 'Pediatric Nurse Practitioner at St. Mary\'s', 'Austin, United States', 'Caring for kids and their families. Volunteer, dog mom, and forever a teacher at heart.', [['Nurse Practitioner', "St. Mary's"]], 'hannah.and.biscuit', 'nurse · golden retriever mom · trail runs · hoping to find a kind partner', ['Trail run with Biscuit, my golden retriever', 'Volunteering at the free clinic, community matters', 'Sunday reset: meal prep and a planner for the week', 'Looking for someone kind, long-term and family-minded']),
  P('Leo Fontaine', 'leo-fontaine-demo', 'Travel Photographer & Filmmaker', 'Toronto, Canada', 'Freelance photographer documenting people and places. 40 countries and counting. Spontaneous by nature.', [['Photographer & Filmmaker', 'Freelance']], 'leo.frames', 'travel · photography · film · spontaneous road trips', ['Road trip through Iceland, shot on film camera', 'Wanderlust again: booking a one-way ticket to Lisbon', 'Backpacking in Patagonia, hiking and photography', 'Film screening and a gallery opening this week']),
  P('Grace Kim', 'grace-kim-demo', 'VP of Engineering at Orbit Payments', 'San Francisco, United States', 'Leading 60 engineers building payments infrastructure. Ambitious, systems-minded, scaling fast.', [['VP of Engineering', 'Orbit Payments']], 'grace.ships', 'eng leader · gym at 5am · routine is freedom', ['5am lifting session, routine is everything', 'Meal prep Sunday with the planner open', 'Scaled the team from 20 to 60, proud', 'Data and metrics nerd at heart']),
  P('Omar Haddad', 'omar-haddad-demo', 'Architect at Studio Noor', 'London, United Kingdom', 'Designing public spaces and housing. Architecture, sketching, and slow mornings in museums.', [['Architect', 'Studio Noor']], 'omar.sketches', 'architecture · sketching · museums · cycling · coffee', ['Sketching in a gallery, architecture of light', 'Cycling along the Thames with espresso in hand', 'Coffee shop crawl in Hackney', 'Reading a novel at a bookstore, quiet Sunday']),
  P('Elena Petrova', 'elena-petrova-demo', 'Ballet Teacher & Arts Nonprofit Director', 'Toronto, Canada', 'Running a nonprofit bringing dance to schools. Teaching ballet and mentoring young dancers.', [['Director', 'Dance For All']], 'elena.dances', 'dance · teaching · community · theater lover', ['Ballet class with the little ones, teaching is joy', 'Broadway trip with friends, theater always', 'Volunteering for the community gala', 'Salsa night, dancing till late, festival weekend']),
  P('Kwame Mensah', 'kwame-mensah-demo', 'Founder at Accra Ventures', 'New York, United States', 'Investing in African startups. Founder, mentor, and relentless builder who believes in long-term partnerships.', [['Founder & Managing Partner', 'Accra Ventures']], 'kwame.invests', 'startups · travel · running · family · looking for a serious relationship', ['Startup demo day in Accra, travel week', 'Half marathon on Sunday, running with friends', 'Mentoring founders on Saturday', 'Looking for a serious long-term partner who loves travel']),
  P('Ingrid Sørensen', 'ingrid-sorensen-demo', 'Data Scientist at Norsk Energi', 'Oslo, Norway', 'Analyst and statistician for renewable energy. Quiet, curious and methodical.', [['Senior Data Scientist', 'Norsk Energi']], 'ingrid.skis', 'skiing · cycling · reading · quiet evenings', ['Skiing trip at dawn, quiet mountains', 'Cycling to work, routine habit in all weather', 'Reading a novel with tea, cozy homebody', 'Data analysis of wind models, research rabbit hole']),
  P('Rafael Costa', 'rafael-costa-demo', 'Startup Founder at Mare Surf Co.', 'Lisbon, Portugal', 'Building sustainable surfwear. Surfer, founder, eternal optimist who loves to host dinners.', [['Founder', 'Mare Surf Co.']], 'rafa.surf', 'surf · sustainable fashion · friends · dinner parties', ['Surf session at dawn, adventure never ends', 'Hosting a dinner party for friends, wine flowing', 'Launched our recycled-ocean-plastic line, sustainability matters', 'Road trip down the coast, spontaneous and free']),
  P('Zoe Adler', 'zoe-adler-demo', 'Elementary School Teacher', 'Chicago, United States', 'Teaching third grade. Mentor to new teachers, book club host, cat mom and dreamer.', [['Teacher', 'Lincoln Elementary']], 'zoe.reads', 'teacher · bookworm · cat mom · board games', ['Book club night hosting with tea, bookworm forever', 'My cat judging my lesson plans, lol', 'Board game night and a quiet cozy evening', 'Volunteering with the library literacy program']),
  P('Ravi Patel', 'ravi-patel-demo', 'Senior Quant at Meridian Trading', 'New York, United States', 'Quantitative researcher. Systems, models, and discipline. Chess on weekends, hot yoga before work.', [['Senior Quant Researcher', 'Meridian Trading']], 'ravi.quant', 'markets · chess · yoga · routine · serious about finding a partner', ['Chess at the park, analysis mode', 'Hot yoga at 6am, routine is a superpower', 'Meal prep Sunday with a planner', 'Looking for a serious relationship with someone thoughtful']),
  P('Chloe Martin', 'chloe-martin-demo', 'Creative Director at Atelier M', 'London, United Kingdom', 'Fashion and art direction. Vintage obsessed, gallery regular, always on a creative mission.', [['Creative Director', 'Atelier M']], 'chloe.styles', 'fashion · vintage · art · live music · friends', ['Vintage thrift haul and styling inspiration', 'Gallery opening then a live music gig', 'Photography shoot with friends, creative chaos lol', 'Festival weekend, party with friends']),
  P('Noah Fischer', 'noah-fischer-demo', 'Software Engineer at Kite', 'Toronto, Canada', 'Backend engineer who likes games, climbing and quiet life. Learning about systems and cooking.', [['Software Engineer', 'Kite']], 'noah.climbs', 'climbing · gaming · cooking · quiet nerd', ['Bouldering session after work, climbing gym regular', 'Video game night with friends, chess later', 'Cooking a new recipe, baking sourdough', 'Learning rust, rabbit hole on systems']),
  P('Amara Diallo', 'amara-diallo-demo', 'Public Health Director at CityCare', 'Chicago, United States', 'Leading a community health team. Director of public health programs, care-driven and determined.', [['Director of Public Health Programs', 'CityCare']], 'amara.moves', 'public health · yoga · running · community · hoping for a serious partner', ['Community health fair volunteer day', 'Morning run then yoga, balance is everything', 'Mentoring young nurses and clinicians', 'Ready for a serious relationship with someone kind']),
  P('Felix Brandt', 'felix-brandt-demo', 'Indie Game Developer', 'Berlin, Germany', 'Making small strange games. Gamer, guitarist, night owl who loves podcasts and a good synth.', [['Game Developer', 'Independent']], 'felix.plays', 'gaming · guitar · live music · podcast addict · cozy', ['New game prototype, gaming is my craft', 'Playing guitar late, songwriting session', 'Gig at a small venue, live music forever', 'Podcast rabbit hole on game design, lol']),
  P('Lucia Romano', 'lucia-romano-demo', 'Sommelier & Wine Importer', 'New York, United States', 'Importing small-producer wines. Sommelier, host, traveler. Love a long dinner and a great story.', [['Founder', 'Romano Selections']], 'lucia.pours', 'wine · travel · food · hosting · adventure', ['Wine tasting trip in Piedmont, travel and taste', 'Hosting dinner for friends, cooking pasta', 'Restaurant tasting menu then cocktails', 'Spontaneous trip to Sicily, adventure calling']),
  P('Jin Park', 'jin-park-demo', 'Director of Product at Waveform', 'Austin, United States', 'Leading product for a music-tech platform. Ambitious, curious, and in love with live music and startups.', [['Director of Product', 'Waveform']], 'jin.listens', 'music · startups · running · concerts · coffee', ['Concert last night, festival season is here', 'Morning 10k then espresso, running routine', 'Startup founder dinner, scaling product', 'Vinyl collection and podcast queue']),
  P('Sara Ibrahim', 'sara-ibrahim-demo', 'Human Rights Lawyer at Open Justice', 'Toronto, Canada', 'Defending asylum seekers. Volunteer, writer, reader. I care deeply and think slowly.', [['Human Rights Lawyer', 'Open Justice']], 'sara.writes', 'law · writing · reading · community · long-term relationship', ['Writing an essay on asylum law, journal at night', 'Volunteering with community legal aid', 'Bookstore wander and a quiet coffee', 'Hoping to find a long-term partner who is kind']),
];
